# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.MailingAddress'),
        ),
        migrations.AddField(
            model_name='owner',
            name='name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(to='property.Owner'),
        ),
    ]
